typography_spectrum: 0.74278
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.17235465324483812
  saturation: 0.4493610898498446
  rhythmicContrast: 0.13168774405494332
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75
analytics:
  google: null
  facebook: null
  twitter: null
name: Yummii Nguyen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This is the headline
description: This is the tagline
purpose: []
